services:
    symbio_webtools.crawler:
        class: %symbio_webtools.crawler.class%
        arguments:
            - @service_container

    symbio_webtools.provider:
        class: %symbio_webtools.provider.class%
        arguments:
            - @service_container
            - @symbio_webtools.crawler
