<?php

namespace Symbio\WebtoolsBundle;

use Symfony\Component\HttpKernel\Bundle\Bundle;

/**
 * This file has been generated by the EasyExtends bundle ( http://sonata-project.org/easy-extends )
 *
 * References :
 *   bundles : http://symfony.com/doc/current/book/bundles.html
 *
 * @author SYMBIO
 */
class SymbioWebtoolsBundle extends Bundle
{
}